/**
 * Names for persisted extension state. Keeping them in one module makes setting
 * ownership auditable and prevents one context from silently writing a near-
 * duplicate key that another context never reads.
 */
export const SETTING_KEY = Object.freeze({
  ACTIVE_TIMER_OPERATION: "active_timer_operation",
  BACKGROUND_SYNC_DUE_AT: "background_sync_due_at",
  CHATGPT_USAGE_SESSION_TOKEN_CONSENT: "chatgpt_usage_session_token_consent",
  CHATGPT_USAGE_STATE: "chatgpt_usage_state",
  CHATGPT_USAGE_GENERATION: "chatgpt_usage_generation",
  DEVICE_ID: "device_id",
  DIAGNOSTIC_RING: "diagnostic_ring",
  DURATION_MULTIPLIER: "duration_multiplier",
  DURATION_MULTIPLIER_SYNCED_AT: "duration_multiplier_synced_at",
  DURATION_MULTIPLIER_UPDATED_AT: "duration_multiplier_updated_at",
  MYSQL_API_BASE_URL: "mysql_api_base_url",
  MYSQL_API_TOKEN: "mysql_api_token",
  MYSQL_REMOTE_CHANGE_TOKEN: "mysql_remote_change_token",
  CLOUDFLARE_D1_API_BASE_URL: "cloudflare_d1_api_base_url",
  CLOUDFLARE_D1_API_TOKEN: "cloudflare_d1_api_token",
  CLOUDFLARE_D1_REMOTE_CHANGE_TOKEN: "cloudflare_d1_remote_change_token",
  REMOTE_BACKEND_ESTABLISHED: "remote_backend_established",
  STORAGE_MIGRATION_STATE: "storage_migration_state",
  RECONCILIATION_INTENTS: "reconciliation_intents",
  REMOTE_BACKEND: "remote_backend",
  STALE_RECONCILIATION_INTENTS: "stale_reconciliation_intents",
  STALE_TIMER_REMINDER_ENABLED: "stale_timer_reminder_enabled",
  STALE_TIMER_REMINDER_STATE: "stale_timer_reminder_state",
  SYNC_BACKOFF_SECONDS: "sync_backoff_seconds",
  SYNC_BACKOFF_UNTIL: "sync_backoff_until",
  SYNC_IDLE_STREAK: "sync_idle_streak",
  SYNC_INTERVAL_SECONDS: "sync_interval_seconds",
  SYNC_LAST_SUCCESS_AT: "sync_last_success_at",
  SYNC_LAST_STATUS: "sync_last_status",
  SYNC_RECOVERY_PENDING: "sync_recovery_pending",
  TEMPO_API_TOKEN: "tempo_api_token",
  TEMPO_AUTHOR_ACCOUNT_ID: "tempo_author_account_id",
  TEMPO_SUBMISSION_LEDGER: "tempo_submission_ledger",
  TEMPO_SUBMISSION_TRACKING_STARTED_AT: "tempo_submission_tracking_started_at",
  TEMPO_PROJECT_TASK_ISSUE_IDS: "tempo_project_task_issue_ids",
  TEMPO_TASK_ISSUE_IDS: "tempo_task_issue_ids",
  UPDATE_AVAILABLE_VERSION: "update_available_version",
  WINDOW_RESIZE_PRESETS: "window_resize_presets",
  WORKDAY_START_HOUR: "workday_start_hour"
});
